const fs = require('fs');

const content = [
  '/**',
  ' * MyMe App - Agent Manage Screen',
  ' * Agent管理页面 - PRD v3.0',
  ' * 显示用户创建的Agent分身列表',
  ' */',
  '',
  'import React, { useEffect, useState, useCallback } from "react";',
  'import {',
  '  View,',
  '  StyleSheet,',
  '  FlatList,',
  '  Alert,',
  '  TouchableOpacity,',
  '  Modal,',
  '  TextInput,',
  '  TouchableWithoutFeedback,',
  '} from "react-native";',
  'import {',
  '  Text,',
  '  Card,',
  '  Chip,',
  '  ActivityIndicator,',
  '  IconButton,',
  '  SegmentedButtons,',
  '  Button,',
  '} from "react-native-paper";',
  'import { useNavigation } from "@react-navigation/native";',
  'import type { NativeStackNavigationProp } from "@react-navigation/native-stack";',
  'import type { AgentStackParamList } from "../../navigation/types";',
  'import { useTheme } from "../../context/ThemeContext";',
  'import { avatarService } from "../../services/avatarService";',
  'import { a2aService } from "../../services/a2aService";',
  'import { useSafeAreaInsets } from "react-native-safe-area-context";',
  '',
  'interface Agent {',
  '  id: string;',
  '  name: string;',
  '  description: string | null;',
  '  scenario: string | null;',
  '  status: string;',
  '  permissions: string[];',
  '  shareCode: string | null;',
  '  createdAt: string;',
  '}',
  '',
  'const SCENARIO_LABELS: Record<string, string> = {',
  '  interview: "面试",',
  '  work: "工作",',
  '  dating: "相亲",',
  '  consultation: "咨询",',
  '};',
  '',
  'export default function AgentManageScreen() {',
  '  const navigation =',
  '    useNavigation<NativeStackNavigationProp<AgentStackParamList>>();',
  '  const { colors } = useTheme();',
  '  const insets = useSafeAreaInsets();',
  '  ',
  '  const [agents, setAgents] = useState<Agent[]>([]);',
  '  const [loading, setLoading] = useState(true);',
  '  ',
  '  const [activeTab, setActiveTab] = useState<"agents" | "relations">("relations");',
  '  const [relations, setRelations] = useState<any[]>([]);',
  '  const [shareModalVisible, setShareModalVisible] = useState(false);',
  '  const [shareCode, setShareCode] = useState("");',
  '',
  '  const loadAgents = useCallback(async () => {',
  '    try {',
  '      const response = await avatarService.getAvatars();',
  '      const list = Array.isArray(response)',
  '        ? response',
  '        : (response.avatars || (response as any).data || []);',
  '      const mappedAgents: Agent[] = list.map((a: any) => ({',
  '        id: a.id,',
  '        name: a.name,',
  '        description: a.description,',
  '        scenario: a.scenario,',
  '        status: a.status,',
  '        permissions: a.permissions,',
  '        shareCode: a.shareCode || null,',
  '        createdAt: a.createdAt || new Date().toISOString(),',
  '      }));',
  '      setAgents(mappedAgents);',
  '    } catch (error) {',
  '      console.error("Failed to load agents:", error);',
  '    }',
  '  }, []);',
  '',
  '  const loadRelations = useCallback(async () => {',
  '    try {',
  '      const response = await a2aService.getRelations();',
  '      setRelations(response.relations || []);',
  '    } catch (error) {',
  '      console.error("Failed to load A2A relations:", error);',
  '    }',
  '  }, []);',
  '',
  '  const loadData = useCallback(async () => {',
  '    setLoading(true);',
  '    await Promise.all([loadAgents(), loadRelations()]);',
  '    setLoading(false);',
  '  }, [loadAgents, loadRelations]);',
  '',
  '  useEffect(() => {',
  '    const unsubscribe = navigation.addListener("focus", loadData);',
  '    return unsubscribe;',
  '  }, [navigation, loadData]);',
  '',
  '  const handleAgentPress = (agent: Agent) => {',
  '    navigation.navigate("AgentDetail", { id: agent.id });',
  '  };',
  '',
  '  const handleCopyShareCode = (shareCode: string) => {',
  '    Alert.alert("分享码", `分享码: ${shareCode}\n\n已复制到剪贴板`, [',
  '      { text: "确定" },',
  '    ]);',
  '  };',
  '',
  '  const renderAgent = ({ item }: { item: Agent }) => (',
  '    <TouchableOpacity onPress={() => handleAgentPress(item)}>',
  '      <Card style={[styles.card, { backgroundColor: colors.surface }]}>',
  '        <Card.Title',
  '          title={item.name}',
  '          subtitle={',
  '            item.description || SCENARIO_LABELS[item.scenario || ""] || "无描述"',
  '          }',
  '          left={(props) => (',
  '            <View style={[styles.avatarText, { backgroundColor: colors.primary }]}>',
  '              <Text style={{ color: colors.textOnPrimary, fontWeight: "bold" }}>',
  '                {item.name.substring(0, 2).toUpperCase()}',
  '              </Text>',
  '            </View>',
  '          )}',
  '          right={(props) => (',
  '            <View style={styles.cardRight}>',
  '              {item.shareCode && (',
  '                <IconButton',
  '                  icon="content-copy"',
  '                  size={20}',
  '                  iconColor={colors.textSecondary}',
  '                  onPress={() => handleCopyShareCode(item.shareCode!)}',
  '                />',
  '              )}',
  '            </View>',
  '          )}',
  '        />',
  '        <Card.Content>',
  '          <View style={styles.permissionsRow}>',
  '            <Text style={[styles.label, { color: colors.textSecondary }]}>',
  '              授权模块:',
  '            </Text>',
  '            <View style={styles.permissionList}>',
  '              {item.permissions.slice(0, 5).map((p) => (',
  '                <Chip',
  '                  key={p}',
  '                  style={[',
  '                    styles.permissionChip,',
  '                    { backgroundColor: colors.surfaceVariant },',
  '                  ]}',
  '                  textStyle={styles.permissionText}',
  '                  compact',
  '                >',
  '                  {p}',
  '                </Chip>',
  '              ))}',
  '              {item.permissions.length > 5 && (',
  '                <Text style={[styles.moreText, { color: colors.textTertiary }]}>',
  '                  +{item.permissions.length - 5}',
  '                </Text>',
  '              )}',
  '            </View>',
  '          </View>',
  '          {item.shareCode && (',
  '            <Text style={[styles.shareCodeText, { color: colors.textTertiary }]}>',
  '              分享码: {item.shareCode}',
  '            </Text>',
  '          )}',
  '        </Card.Content>',
  '      </Card>',
  '    </TouchableOpacity>',
  '  );',
  '',
  '  return (',
  '    <View style={[styles.container, { backgroundColor: colors.background }]}>',
  '      <View',
  '        style={[',
  '          styles.header,',
  '          { backgroundColor: colors.primary, paddingTop: insets.top + 8 },',
  '        ]}',
  '      >',
  '        <Text style={[styles.title, { color: colors.textOnPrimary }]}>',
  '          Agent管理',
  '        </Text>',
  '        <IconButton',
  '          icon="plus"',
  '          iconColor={colors.textOnPrimary}',
  '          size={24}',
  '          onPress={() => {',
  '            if (activeTab === "agents") {',
  '              navigation.navigate("AgentCreate" as any, {} as any);',
  '            } else {',
  '              setShareModalVisible(true);',
  '            }',
  '          }}',
  '        />',
  '      </View>',
  '      <View style={styles.tabContainer}>',
  '        <SegmentedButtons',
  '          value={activeTab}',
  '          onValueChange={(value) => setActiveTab(value as "agents" | "relations")}',
  '          buttons={[',
  '            { value: "relations", label: "Agent关系" },',
  '            { value: "agents", label: "我的Agent" },',
  '          ]}',
  '          style={styles.segmentedButtons}',
  '        />',
  '      </View>',
  '',
  '      {loading ? (',
  '        <View style={styles.loading}>',
  '          <ActivityIndicator size="large" color={colors.primary} />',
  '        </View>',
  '      ) : activeTab === "agents" ? (',
  '        <FlatList',
  '          data={agents}',
  '          renderItem={renderAgent}',
  '          keyExtractor={(item) => item.id}',
  '          contentContainerStyle={styles.list}',
  '         
